### ISSUE TITLE
Component is not found in path "pages/index/plugin:/wx6b6cb15df2836ebe/yycalendar"

### ISSUE THREAD

**Issue by enjoydegame** [79458627/ttyy-calendar#2]
按照步骤, 出现了这个错误
Component is not found in path "pages/index/plugin:/wx6b6cb15df2836ebe/yycalendar" (using by "pages/index/addOrder")
Error: Component is not found in path "pages/index/plugin:/wx6b6cb15df2836ebe/yycalendar" (using by "pages/index/addOrder")
    at e (http://127.0.0.1:16646/appservice/__dev__/WAService.js:13:29011)
    at e (http://127.0.0.1:16646/appservice/__dev__/WAService.js:13:29163)
    at W (http://127.0.0.1:16646/appservice/__dev__/WAService.js:14:3348)
    at Object.t.addView (http://127.0.0.1:16646/appservice/__dev__/WAService.js:14:4358)
    at Function.value (http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:28964)
    at B (http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:7087)
    at L (http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:8367)
    at q (http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:9688)
    at Function.<anonymous> (http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:12171)
    at http://127.0.0.1:16646/appservice/__dev__/WAService.js:15:17917

**Comment by rangang** [comment]
解决了吗，需要我这边优化什么
